pluginManagement {
    repositories {
        gradlePluginPortal()
        google()
        mavenCentral()
        mavenLocal()
    }
}

rootProject.name = 'osmdroid-lostrat'

//this is the normal settings.gradle file for osmdroid, which defines which modules are included
//in the build process. Default is everything

//libraries
include ':osmdroid-android'
include ':osmdroid-mapsforge'
include ':osmdroid-geopackage'
include ':osmdroid-wms'
include ':osmdroid-shape'

//sample apps
include ':OpenStreetMapViewer'
include ':osmdroid-simple-map'

//jdk specific tools and applications
include ':OSMMapTilePackager'
include ':osmdroid-server-jdk'

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        mavenLocal()
        maven {
            url = "https://oss.sonatype.org/content/repositories/snapshots"
            mavenContent {
                snapshotsOnly()
            }
        }
        maven { url = uri("https://jitpack.io") }   // <-- add this
    }
}

